name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Or your default branch name
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write # Needed for pushing to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x" # Updated to Node 22.x to match your local environment
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Create CNAME file for custom domain
        run: echo "tabirkeland.com" > ./dist/CNAME

      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll

      # Optional step to debug the output directory if needed
      - name: List build output files
        run: ls -la ./dist

      # Create a vercel.json file instead of _headers
      - name: Create vercel.json for MIME types
        run: |
          echo '{
            "headers": [
              {
                "source": "/(.*)\\.js$",
                "headers": [
                  {
                    "key": "Content-Type",
                    "value": "application/javascript"
                  }
                ]
              },
              {
                "source": "/(.*)\\.mjs$",
                "headers": [
                  {
                    "key": "Content-Type",
                    "value": "application/javascript"
                  }
                ]
              }
            ]
          }' > ./dist/vercel.json

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Vite builds to dist folder
          branch: gh-pages # The branch to deploy to
          clean: true # Automatically remove deleted files from the deploy branch
